services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=master@123
    ports:
      - "1433:1433"

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - Jwt__Authority=http://localhost:8081
    depends_on:
      - stock
      - sales

  stock:
    build:
      context: ./services/stock
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_URLS=http://+:5001
      - ConnectionStrings__Default=Server=sqlserver;Database=StockDb;User Id=sa;Password=master@123;TrustServerCertificate=true;
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__User=guest
      - RabbitMQ__Pass=guest
      - Jwt__Authority=http://localhost:8081
    depends_on:
      - sqlserver
      - rabbitmq

  sales:
    build:
      context: ./services/sales
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_URLS=http://+:5002
      - ConnectionStrings__Default=Server=sqlserver;Database=SalesDb;User Id=sa;Password=master@123;TrustServerCertificate=true;
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__User=guest
      - RabbitMQ__Pass=guest
      - Jwt__Authority=http://localhost:8081
    depends_on:
      - sqlserver
      - rabbitmq
